feat: security,jwt,로그인 #9
TeamCrops/good-crop pull request #19
Opened 2024-11-25 11:59 UTC by JIMINJI1

## 🔘 담당 파트
- Spring security
- Jwt 
- 로그인

## 🔎 작업 상세 내용
- Spring security 
- Jwt 토큰 생성 및 유효성 검사
- 인증/인가 필터
- Filter에서 로그인 처리
-  사용자 인증  UserDetailsImpl 및 UserDetailsServiceImpl 

## 🔧 앞으로의 과제

## ➕ 이슈 링크
- #9

2024-11-25 12:04 UTC, gaeul79 approved these changes
확인했습니다~

2024-11-25 14:11 UTC, Eun-0 reviewed
화이팅!!!

2024-11-25 15:32 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/filter/JwtAuthorizationFilter.java
> +        return new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
네 해당 부분 수정했습니다~

2024-11-25 15:32 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/filter/JwtAuthorizationFilter.java
> +                url.matches("/api/products/\\d+/reviews")) {
네 해당 부분 수정했습니다~

2024-11-25 15:32 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/filter/JwtAuthorizationFilter.java
> +                url.startsWith("/api/products") ||
네 해당 부분 수정했습니다~

2024-11-25 15:32 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/filter/JwtAuthenticationFilter.java
> +        setFilterProcessesUrl("/api/auth/signin");
네 해당 부분 수정했습니다~

2024-11-25 15:32 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/entity/UserDetailsImpl.java
> +    public Collection<? extends GrantedAuthority> getAuthorities() {
네 주석 수정 했습니다~

2024-11-25 15:33 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/config/WebSecurityConfig.java
> +                                .requestMatchers("/api/products/{productId}/reviews").permitAll()
네 해당 부분 수정했습니다~

2024-11-25 15:33 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/config/WebSecurityConfig.java
> +                                .requestMatchers("/api/products/**").permitAll()
네 해당 부분 수정했습니다~

2024-11-25 16:24 UTC, Eun-0 requested changes
확인 부탁드립니다~

2024-11-25 16:24 UTC, Eun-0 commented on src/main/java/com/crop/goodcrop/security/filter/JwtAuthenticationFilter.java
> +        setFilterProcessesUrl("/api/auth/signin");
이 부분은 코드나 API 명세서, 둘 중 어느 것도 수정되지 않은 것 같습니다

다시 한 번 확인 부탁드립니다~

2024-11-26 00:03 UTC, JIMINJI1 commented on src/main/java/com/crop/goodcrop/security/filter/JwtAuthenticationFilter.java
> +        setFilterProcessesUrl("/api/auth/signin");
네 API 명세서 수정했습니다~

2024-11-26 01:01 UTC, Eun-0 commented on src/main/java/com/crop/goodcrop/security/filter/JwtAuthenticationFilter.java
> +        setFilterProcessesUrl("/api/auth/signin");
확인했습니당~

2024-11-26 01:01 UTC, Eun-0 approved these changes

2024-11-26 01:02 UTC, Eun-0 commented
수고하셨습니다!!!!!!!!

2024-11-26 01:03 UTC, merged